spring:
  datasource:
    url: "jdbc:mysql://ls-5e1f6dc6cda34ee3ff0a83dddc17e6772c6fe068.cpd3bfmvavpa.ap-northeast-2.rds.amazonaws.com:3306/bakeryproject"
    username : dbmasteruser
    password:  
    
mybatis:
  mapper-locations: mapper/*.xml
  
jwt:
  signingKey: 123456789 
  expirationDateInMs : 40000000
  refreshExpirationDateInMs: 900000000
  secret : "bakery"
  
cloud:
  aws:
    s3:
      bucket: bakeryimage
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      accessKey: 
      secretKey: 